import { useEffect, useState } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { db } from "@/lib/firebase";
import { collection, getDocs, doc, updateDoc } from "firebase/firestore";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Handshake, CheckCircle, Clock, FileText } from "lucide-react";
import { toast } from "@/hooks/use-toast";
import jsPDF from "jspdf";

interface Deal {
  id: string;
  wasteListingId: string;
  buyerFactoryId: string;
  sellerFactoryId: string;
  wasteType: string;
  status: "pending" | "accepted" | "completed";
  co2Saved: number;
  distanceKm: number;
  compatibilityScore: number;
  createdAt?: any;
}

const statusConfig = {
  pending: { label: "Pending", variant: "outline" as const, icon: Clock },
  accepted: { label: "Accepted", variant: "secondary" as const, icon: CheckCircle },
  completed: { label: "Completed", variant: "default" as const, icon: CheckCircle },
};

const Deals = () => {
  const { user } = useAuth();
  const [deals, setDeals] = useState<Deal[]>([]);
  const [loading, setLoading] = useState(true);

  const load = async () => {
    if (!user) return;
    setLoading(true);
    const snap = await getDocs(collection(db, "deals"));
    const all = snap.docs
      .map((d) => ({ id: d.id, ...d.data() } as Deal))
      .filter((d) => d.buyerFactoryId === user.uid || d.sellerFactoryId === user.uid);
    setDeals(all);
    setLoading(false);
  };

  useEffect(() => { load(); }, [user]);

  const updateStatus = async (id: string, status: "accepted" | "completed") => {
    await updateDoc(doc(db, "deals", id), { status });
    toast({ title: `Deal ${status}!` });
    load();
  };

  const generatePDF = (deal: Deal) => {
    const pdf = new jsPDF();
    pdf.setFontSize(20);
    pdf.text("punarCYCLE — Waste Transfer Manifest", 20, 25);
    pdf.setFontSize(12);
    pdf.text(`Deal ID: ${deal.id}`, 20, 45);
    pdf.text(`Waste Type: ${deal.wasteType}`, 20, 55);
    pdf.text(`Status: ${deal.status}`, 20, 65);
    pdf.text(`Compatibility Score: ${deal.compatibilityScore}%`, 20, 75);
    pdf.text(`Distance: ${deal.distanceKm} km`, 20, 85);
    pdf.text(`CO₂ Saved: ${deal.co2Saved} kg`, 20, 95);
    pdf.text(`Date: ${new Date().toLocaleDateString()}`, 20, 105);
    pdf.setFontSize(10);
    pdf.text("This document is auto-generated by punarCYCLE platform.", 20, 130);
    pdf.text("Reuse · Trade · Sustain", 20, 140);
    pdf.save(`punarCYCLE-deal-${deal.id.slice(0, 8)}.pdf`);
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-display font-bold flex items-center gap-2">
          <Handshake className="h-6 w-6 text-primary" /> Deal Flow
        </h1>
        <p className="text-muted-foreground">Track and manage your waste exchange deals.</p>
      </div>

      {loading ? (
        <div className="text-center py-12"><div className="h-8 w-8 animate-spin rounded-full border-4 border-primary border-t-transparent mx-auto" /></div>
      ) : deals.length === 0 ? (
        <Card>
          <CardContent className="py-12 text-center">
            <Handshake className="h-12 w-12 mx-auto text-muted-foreground/50 mb-4" />
            <p className="text-muted-foreground">No deals yet. Check your AI matches to initiate deals!</p>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-4">
          {deals.map((d) => {
            const cfg = statusConfig[d.status];
            return (
              <Card key={d.id} className="hover:shadow-md transition-shadow">
                <CardContent className="py-5">
                  <div className="flex flex-col md:flex-row md:items-center gap-4">
                    <div className="flex-1 space-y-2">
                      <div className="flex items-center gap-3">
                        <h3 className="font-semibold capitalize">{d.wasteType}</h3>
                        <Badge variant={cfg.variant}>{cfg.label}</Badge>
                      </div>
                      <div className="flex items-center gap-4 text-sm text-muted-foreground">
                        <span>Score: {d.compatibilityScore}%</span>
                        <span>{d.distanceKm} km</span>
                        <span>CO₂: {d.co2Saved} kg saved</span>
                      </div>
                      <p className="text-xs text-muted-foreground">Deal ID: {d.id.slice(0, 12)}...</p>
                    </div>
                    <div className="flex items-center gap-2 flex-wrap">
                      {d.status === "pending" && (
                        <Button size="sm" onClick={() => updateStatus(d.id, "accepted")}>Accept</Button>
                      )}
                      {d.status === "accepted" && (
                        <Button size="sm" onClick={() => updateStatus(d.id, "completed")}>Mark Complete</Button>
                      )}
                      <Button size="sm" variant="outline" onClick={() => generatePDF(d)}>
                        <FileText className="h-4 w-4 mr-1" /> PDF
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default Deals;
